sudo: required

services:
  - docker

language: bash

env:
  global:
    # DOCKER_EMAIL
    - secure: "aD4eQSYRLrKrrFVV88ksjC1kJPZ+jqu8pZPgh8OC3WQrZmPMVEvBJ4ojw1Ns/Mj3ssDpJ7xlxuCm1pCoXK77dJylDn2kVTuOdkRci9QUt3ZV/lLOOYFnGVh+GSLyqNxURViDOeFzFk5m/IkHoeGjNx1XiLup/LLs+lj99fGfq7SNH98z6c78AGIEbmSJ2T/hg8lJJ1jw52L3Dz3cRcAO6Gyy9t/+MmhEGVRrkFtRzYFjaHqSWpDXmdQf13Pf59zNgyyQFNxMVBmVFmof9fg20lWYbLY+bqltxcBqmKqEb1YxnOQ0OmWgFzp1BR5Fq/33BdpSbF36j9f3Gx9ECZSei6no71xWfvsFNjj0NXBsRu1un7cEvJkqEHsfRR86aK+gtWEJg+bWrkZTUl4BvM0Gv7hfldJSLeFYeWNDrVvvHmR733sBvsCU5WSNUXgvMk5v9iJkSgAmL6HRo5r/N/2YUZ/QcudOnff1ApAE6yLRzhkM7MDnO9wvbNBKJus7izw+ke8Wktg2i9Gk9f0p4j+rm1O7McsKTIJ6kJSU5MxFJokljWjlegDSX7ad9w5tUb10QYM0dZ1ZHeVg7y0hImh0P/ldebzk8etGztF077H0/roDBsqP6WeoSk+XOr4UPutSVEiTuZRBFTa5KNfeG3178gd/OoT+AwMA0+IwDpny2ls="
    # DOCKER_USER
    - secure: "EcQUC0ttoRmJHZC6fpH5NqfTne/ZusCQi8JZNfAdXPTNF3ftxz0DPqVkmm9CMltYIOedM+xFwr9anFZB/zLGx21qxQuRHaHPMWq5/sd2QI8DnYgN+HpUYpCVBsGBLjO6TgIFq+y70Anvfs5Zn8D/1BZJ8whuQwWNKhPg+zHSDjQ/vkKLlcAtseSjvvX9fIubBrp+ZDkqSOn6gwgssmUaPbA5k/+G/LZU8GFoIUNLQPKxYn9KTraNxSWQqfPIUrT7vWKgATA9BrF0B5+OUvByy68hY7HKuIFbJBOryOOST3TOIjeuhv8QWF0IensT8pgHBCiduj+jZoFzXGR+vt63nACJWei9RFDiyjm5VQvZrLwJURDLMP1kn5jsjTUHNPfElUhwdX17sK6dG4QfSo9+KQjmFTSdBIr1hzIntrqlO1st1f8Yqc0a2gPdSXwSDe/kqs0LGzE58iAsfikoU8P1GEq/p9VlfDYL4Xajhr0H2FAyQg2JmteXrCqC6jYWsjWsLGS3OZstcSAFNxGR5b6/gPcsN33zjKTVskp7922JVr5WuA3FMl2f9pHCPna31Ypacl+pP2lidEKHIjgAfI/Hak3gBPeWG6by+QgYsTsvaeRjE/Lg814D3bEIoNoa9lcp8eeiigUbbB7SDAZXbZ20tppwAt9jjwv4P2CrGuGwbmg="
    # DOCKER_PASS
    - secure: "iJ7lEEj/Cub2st1Q7of7y7Diz4KXgXsHgKxZ20v19y5SolQ3W0E/nugcGKqz1mznryFPVxKH/SwG17TMqhFrgIaaDF90Rjs79PqwMuJ7MCNOTeYIXwWVVvpIWCBwzZ65yCcHQtwRS35LWw6+BbsqvZakrrwOpMBhRGIZVUHRsEtZSaOZpnLwJymzDnCJrrlE3r1zu4L3WjYYwAkQ4bz4BPH3os0pbJAHXaPaRJuVVPB4fyvIshFAF6aqz60x2mzpS7y8erZ+IOh0urUyzxR7H6RuntyL84+ATZyGweYpfuQPNyD7pZjHCVDabQSvK+/n5VrsWAIX5RheCYGv+a6HtJsX8L6RXPFMk8N82Feo97YiqcFhxSKKL+8rrQ51j9My0Odkx3z39l0j2PP0Z4rDLy8QwPmGqtDZOX/iXCOTMcPHq4Zlb4X/yS6mfHmyO/wigKfYPmrGEVqFT5JhQctgSsUlWSbHvw1vPrZk7g7YBdUbBb2Xd9RCwzuBmuC8ytq0bKnabqlJhIOB4027DmtZA70ECdEEUxE5a8w8hutuW9UWiCnZzpIcbG2s662Qy6/AdpGzxHUBxwHoHAP+P0Qa7u6JhErsqt5DIdzAezqKQrDS/fi4TPcYCYusGeaVjMlVuzZycwO8EOvrV2WNKlPRNc8MMyvj7g7KVibEKer8bwk="
    - GIT_BRANCH=$(git ls-remote origin | sed -n "\|$TRAVIS_COMMIT\s\+refs/heads/|{s///p}")

script:
  - git submodule update --init
  - curl -O -L https://github.com/Hellslicer/rocker/releases/download/1.3.4/rocker_linux_amd64.tar.gz
  - tar xvf rocker_linux_amd64.tar.gz
  - cd code/
  - 'if [ -z "$TRAVIS_TAG" ]; then ../rocker build --build-arg JOB_SLOTS=$(nproc); fi'
  - 'if [ ! -z "$TRAVIS_TAG" ]; then ../rocker build --build-arg JOB_SLOTS=$(nproc) --build-arg CI_BRANCH=${GIT_BRANCH} --build-arg CI_BUILD_NUMBER=${TRAVIS_TAG} --auth $DOCKER_USER:$DOCKER_PASS --push; fi'
