[package]
name = "cfx-wasm-runtime"
version = "0.1.0"
authors = ["ZOTTCE <zottce@gmail.com>"]
edition = "2018"

[dependencies]
wasmtime = "0.27.0"
wasmtime-wasi = "0.27.0"
fivem-core = { path = "../bindings/core", default-features = false, features = ["types"] }
anyhow = "1.0"
